services:

  auth-db:
    image: postgres:18
    container_name: auth-db
    restart: always
    expose:
      - "5432"
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASS}
    volumes:
      - auth_data:/var/lib/postgresql

  map-db:
    image: postgres:18
    container_name: map-db
    restart: always
    expose:
      - "5432"
    environment:
      POSTGRES_DB: ${MAP_DB_NAME}
      POSTGRES_USER: ${MAP_DB_USER}
      POSTGRES_PASSWORD: ${MAP_DB_PASS}
    volumes:
      - map_data:/var/lib/postgresql

  auth-service:
    image: 093235337983.dkr.ecr.eu-central-1.amazonaws.com/cli-team/auth-service:v1
    expose:
      - "8000"
    depends_on:
      - auth-db
    environment:
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY:?}  
      ALLOWED_HOSTS: ${AUTH_ALLOWED_HOSTS}
      DAILYPASS_SERVICE_URL: ${DAILYPASS_SERVICE_URL}
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASS}
      DB_HOST: auth-db

  daycode-service:
    image: 093235337983.dkr.ecr.eu-central-1.amazonaws.com/cli-team/dailycode-service:v1
    expose: 
      - "9090"
    volumes:
      - type: bind
        source: ./passcode.txt
        target: /app/passcode.txt

  map-service:
    image: 093235337983.dkr.ecr.eu-central-1.amazonaws.com/cli-team/map-service:v1
    expose:
      - "8001"
    depends_on:
      - map-db
    environment:
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY:?}   
      ALLOWED_HOSTS: ${MAP_ALLOWED_HOSTS}
      POSTGRES_DB: ${MAP_DB_NAME}
      POSTGRES_USER: ${MAP_DB_USER}
      POSTGRES_PASSWORD: ${MAP_DB_PASS}
      DB_HOST: map-db
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_STORAGE_BUCKET_NAME: ${AWS_STORAGE_BUCKET_NAME}
      AWS_S3_REGION_NAME: ${AWS_S3_REGION_NAME}

  frontend:
    image: 093235337983.dkr.ecr.eu-central-1.amazonaws.com/cli-team/frontend:v1
    expose:
      - "80"
    depends_on:
      - auth-service
      - map-service

  reverse-proxy:
    image: 093235337983.dkr.ecr.eu-central-1.amazonaws.com/cli-team/reverse-proxy:v1
    depends_on:
    - frontend
    - auth-service
    - map-service
    ports:
      - "7000:80"


  migration_auth:
    image: 093235337983.dkr.ecr.eu-central-1.amazonaws.com/cli-team/auth-service:v1
    command: ["python3", "manage.py", "migrate"]
    depends_on:
      - auth-db
    environment:
      SECRET_KEY: ${SECRET_KEY:?}
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASS}
      DB_HOST: auth-db

  migration_map:
    image: 093235337983.dkr.ecr.eu-central-1.amazonaws.com/cli-team/map-service:v1
    command: ["python3", "manage.py", "migrate"]
    depends_on:
      - map-db
    environment:
      POSTGRES_DB: ${MAP_DB_NAME}
      POSTGRES_USER: ${MAP_DB_USER}
      POSTGRES_PASSWORD: ${MAP_DB_PASS}
      DB_HOST: map-db

volumes:
  auth_data:
  map_data:
