server {
  listen       80;
  listen  [::]:80;
  server_name  localhost;

  location / {
    proxy_pass http://frontend;
  }

  location /api/login {
    proxy_pass http://auth-service:8000;
  }
  location /api/register {
    proxy_pass http://auth-service:8000;
  }
  location /api/token/refresh {
    proxy_pass http://auth-service:8000;
  }
  location /api/logout {
    proxy_pass http://auth-service:8000;
  }

  location /api/sighting {
    proxy_pass http://map-service:8001;
  }
}